### ISSUE TITLE
clap version 4.15.--- and rustc incompatibility

### ISSUE THREAD

**Issue by skyking1996** [Devolved-AI/Argochain#21]
workaround: rustup override set stable

**Comment by skyking1996** [comment]
package `clap v4.5.3` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.73.0-nightly

**Comment by skyking1996** [comment]
> package `clap v4.5.3` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.73.0-nightly

For context, rustc 1.8-.-nightly was installed, but not recognized. Had to override to get it to work.

**Comment by psyferlab** [comment]
We will try to add some rust-toolchain.toml files in order to prevent this from happening in the future. Good catch, thank you!
