### ISSUE TITLE
Nodes won't communicate when not on local machine.

### ISSUE THREAD

**Issue by psyferlab** [Devolved-AI/Argochain#8]
- [] When we create two nodes from the same computer locally, communication between the two nodes works fine. However, when attempting to communicate between two nodes remotely, it does not work. We have customized our Argochain based on our requirements. Currently, we are conducting research to resolve these issues.

## For Rust Programming language:

| Resource | Link |
|----------|------|
| The Rust Book: Contains pretty much everything you need to know about Rust. | [Link](https://doc.rust-lang.org/nightly/book/) |
| Rustlings: Small exercises to get you used to reading and writing Rust code. | [Link](https://github.com/rust-lang/rustlings) |
| Exercism Rust Track: Learn Rust by doing exercises! | [Link](https://exercism.org/tracks/rust) |
| Learning Rust: More stuff to learn from is always better! | [Link](https://learning-rust.github.io/) |
| This Week In Rust: A weekly newsletter about Rust updates, featured crates, job offers, ongoing pull requests, and a lot more! | [Link](https://this-week-in-rust.org/) |
| Rust By Example: A nice tutorial for people who already know how to program. | [Link](https://doc.rust-lang.org/stable/rust-by-example/) |
| Rust First Steps: Microsoft's own Rust tutorial. | [Link](https://docs.microsoft.com/en-gb/learn/paths/rust-first-steps/) |
| Tour of Rust: A step by step guide through the features of the Rust programming language. | [Link](https://tourofrust.com/) |
| The Little Book of Rust Macros: Everything you need to know about macros. | [Link](https://veykril.github.io/tlborm/) |
| Learn Rust Page: Index for Rust's documentation page. Includes things such as the Edition Guide, Cargo Book, etc. | [Link](https://www.rust-lang.org/learn) |
| Awesome Rust: A huge list of the best crates and tools you could possibly think of! | [Link](https://github.com/kud1ing/awesome-rust) |
| Rust FFI Omnibus: How to use Rust code in other languages | [Link](https://jakegoulding.com/rust-ffi-omnibus/) |
| Rust Cheatsheet: List of a bunch of common Rust knowledge. | [Link](https://cheats.rs/) |

**Comment by psyferlab** [comment]
@mitun567 @Rezvi90 @nazmuldevolvedai @humayun-ahmad 

It is never acceptable to write internal notes on the Github repo itself. 

You MUST open an issue or start a discussion.

Never do what is in the picture below ever again:
<img width="1350" alt="Screenshot 2024-04-07 at 12 00 33 AM" src="https://github.com/Devolved-AI/Argochain/assets/96510238/22a55699-d2ce-4b61-beae-18f12816645b">

**Comment by humayun-ahmad12** [comment]
Issue solved
